#server configuration
server:
    port: ${PORT}
    #error:
        #include-stacktrace: never

#spring configuration
spring:
    application:
        name: LifeMaster

#image configuration size
    servlet: 
        multipart: 
            max-file-size: 10MB
            max-request-size: 10MB
#datasource
    datasource:
        url: ${DB_URL_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa: 
        database-platform: org.hibernate.dialect.PostgreSQLDialect 
        show-sql: false
        hibernate: 
            ddl-auto: none # Opciones: create, create-drop, update, validate, none

#Open api swagger ui 
springdoc: 
    api-docs: 
        path: /api-docs
    swagger-ui:
        persist-authorization: true
        tags-sorter: alpha
        doc-expansion: list  # none | list | full

#prefix endpoints configuration
api:
    prefix: ${PREFIX} 

#secret jwt
jwt:
    secret: ${JWT_SECRET}

swg:
    server:
        url: ${SERVER_URL}
        description: ${SERVER_DESCRIPTION}