#server configuration
server:
    port: ${PORT}
    #error:
        #include-stacktrace: never

#spring configuration
spring:
    application:
        name: LifeMaster

#image configuration size
    servlet: 
        multipart: 
            max-file-size: 10MB
            max-request-size: 10MB
#datasource
    datasource:
        url: jdbc:postgresql://${DB_URL}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa: 
        database-platform: org.hibernate.dialect.PostgreSQLDialect 
        show-sql: true
        hibernate: 
            ddl-auto: create # Opciones: create, create-drop, update, validate, none

#Open api swagger ui 
springdoc: 
    api-docs: 
        path: /api-docs
    swagger-ui:
        persist-authorization: true

#prefix endpoints configuration
api:
    prefix: ${PREFIX} 

#secret jwt
jwt:
    secret: ItSDaNG3r0UsT06oAl0n3TaK3ThIs2025